-- Migration 002: Create Tasks Table (Step 27)
CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  status ENUM('pending', 'in_progress', 'completed') DEFAULT 'pending',
  priority ENUM('low', 'medium', 'high') DEFAULT 'medium',
  category VARCHAR(100) DEFAULT 'General',
  estimated_duration INT DEFAULT 30,
  actual_duration INT DEFAULT 0,
  duration_unit VARCHAR(20) DEFAULT 'minutes',
  due_date VARCHAR(20) NULL,
  due_time VARCHAR(20) NULL,
  planned_date VARCHAR(20) NULL,
  planned_start_time VARCHAR(20) NULL,
  goal_id VARCHAR(100) NULL,
  project_id VARCHAR(100) NULL,
  recurring_task_id VARCHAR(100) NULL,
  occurrence_date VARCHAR(20) NULL,
  tags JSON NULL,
  task_notes TEXT NULL,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_tasks_user_id (user_id),
  INDEX idx_tasks_status (status),
  INDEX idx_tasks_due_date (due_date),
  INDEX idx_tasks_planned_date (planned_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
